### ISSUE TITLE
gfaTools can not be found

### ISSUE THREAD

**Issue by dheerajdhotre** [pieterjanvc/mgs2amr#9]
I have installed most of the things successfully but now facing issue with gfaTools
It is installed on a system but when I run ./setup.sh it says
(base) nccs@nccs:/opt/softwares/mgs2amr/mgs2amr-2.0.0-beta$ ./setup.sh
16:08:10 - Start the setup check...

1) Check dependencies...
 - SQLite 3 is present
 - The mgs2amr database is present

--- ERROR LINE 109 ---

Error: The ''gfaTools'' package needs to be installed manually (not on CRAN).It can be found in the mgs2amr root folder.
Open R and run:
 install.packages("gfaTools_<version>.tar.gz")
Execution halted

1. gfatools is already installed and in the path gfatools: /opt/softwares/mgs2amr/gfatools/gfatools
2. I can not find it in mgs2amr root folder
3. I failed to install it manually from R as it is not found on CRAN and is also not available to install from conda

Please suggest

**Comment by pieterjanvc** [comment]
Hello,

In order to install gfaTools, you need to run the following command in R
```
install.packages("gfaTools_.tar.gz", repos = NULL)
```
_You should now see the package being compiled_

* Make sure you don't just unzip the package somewhere (as it seems you did with "/opt/softwares/mgs2amr/gfatools/gfatools"), the library needs to be compiled by R
* Check that you install in the same R version and library as all the other packages. You can check that it works by opening R and running `library(gfaTools)` after installation
